[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2021"
license = "GPL-3.0"
name = "namada"
resolver = "2"
version = "0.13.3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["abciplus"]
mainnet = [
  "namada_core/mainnet",
]
# NOTE "dev" features that shouldn't be used in live networks are enabled by default for now
dev = []
ferveo-tpke = [
  "namada_core/ferveo-tpke",
]
wasm-runtime = [
  "namada_core/wasm-runtime",
  "loupe",
  "parity-wasm",
  "pwasm-utils",
  "rayon",
  "wasmer-cache",
  "wasmer-compiler-singlepass",
  "wasmer-engine-dylib",
  "wasmer-engine-universal",
  "wasmer-vm",
  "wasmer",
]
# Enable queries support for an async client
async-client = [
  "async-trait",
]
# tendermint-rpc support
tendermint-rpc = [
  "async-client",
  "dep:tendermint-rpc",
]
tendermint-rpc-abcipp = [
  "async-client",
  "dep:tendermint-rpc-abcipp",
]

abcipp = [
  "namada_core/abcipp",
  "ibc-proto-abcipp",
  "ibc-abcipp",
  "tendermint-abcipp",
  "tendermint-proto-abcipp",
  # it's OK to include the tendermint-rpc feature here, as we aren't currently building wasms with `abcipp`
  "tendermint-rpc-abcipp",
]
abciplus = [
  "namada_core/abciplus",
  "namada_proof_of_stake/abciplus",
  "ibc",
  "ibc-proto",
  "tendermint",
  "tendermint-proto",
]

ibc-mocks = [
  "namada_core/ibc-mocks",
]
ibc-mocks-abcipp = [
  "namada_core/ibc-mocks-abcipp",
]

# for integration tests and test utilies
testing = [
  "namada_core/testing",
  "namada_proof_of_stake/testing",
  "async-client",
  "proptest",
  "tempfile",
]

[dependencies]
namada_core = {path = "../core", default-features = false, features = ["secp256k1-sign-verify"]}
namada_proof_of_stake = {path = "../proof_of_stake", default-features = false}
async-trait = {version = "0.1.51", optional = true}
bellman = "0.11.2"
bls12_381 = "0.6.1"
borsh = "0.9.0"
circular-queue = "0.2.6"
# Using unreleased commit on top of version 0.5.0 that adds Sync to the CLruCache
clru = {git = "https://github.com/marmeladema/clru-rs.git", rev = "71ca566"}
data-encoding = "2.3.2"
derivative = "2.2.0"
# TODO using the same version of tendermint-rs as we do here.
ibc-abcipp = {package = "ibc", git = "https://github.com/heliaxdev/ibc-rs", rev = "9fcc1c8c19db6af50806ffe5b2f6c214adcbfd5d", default-features = false, optional = true}
ibc-proto-abcipp = {package = "ibc-proto", git = "https://github.com/heliaxdev/ibc-rs", rev = "9fcc1c8c19db6af50806ffe5b2f6c214adcbfd5d", default-features = false, optional = true}
ibc = {version = "0.14.0", default-features = false, optional = true}
ibc-proto = {version = "0.17.1", default-features = false, optional = true}
itertools = "0.10.0"
loupe = {version = "0.1.3", optional = true}
parity-wasm = {version = "0.45.0", features = ["sign_ext"], optional = true}
paste = "1.0.9"
# A fork with state machine testing
proptest = {git = "https://github.com/heliaxdev/proptest", branch = "tomas/sm", optional = true}
prost = "0.9.0"
pwasm-utils = {git = "https://github.com/heliaxdev/wasm-utils", tag = "v0.20.0", features = ["sign_ext"], optional = true}
rayon = {version = "=1.5.3", optional = true}
rust_decimal = "1.26.1"
rust_decimal_macros = "1.26.1"
serde_json = "1.0.62"
sha2 = "0.9.3"
# We switch off "blake2b" because it cannot be compiled to wasm
tempfile = {version = "3.2.0", optional = true}
tendermint-abcipp = {package = "tendermint", git = "https://github.com/heliaxdev/tendermint-rs", rev = "95c52476bc37927218374f94ac8e2a19bd35bec9", optional = true}
tendermint-rpc-abcipp = {package = "tendermint-rpc", git = "https://github.com/heliaxdev/tendermint-rs", rev = "95c52476bc37927218374f94ac8e2a19bd35bec9", features = ["http-client"], optional = true}
tendermint-proto-abcipp = {package = "tendermint-proto", git = "https://github.com/heliaxdev/tendermint-rs", rev = "95c52476bc37927218374f94ac8e2a19bd35bec9", optional = true}
tendermint = {version = "0.23.6", optional = true}
tendermint-rpc = {version = "0.23.6", features = ["http-client"], optional = true}
tendermint-proto = {version = "0.23.6", optional = true}
thiserror = "1.0.30"
tracing = "0.1.30"
wasmer = {version = "=2.2.0", optional = true}
wasmer-cache = {version = "=2.2.0", optional = true}
wasmer-compiler-singlepass = {version = "=2.2.0", optional = true}
wasmer-engine-dylib = {version = "=2.2.0", optional = true}
wasmer-engine-universal = {version = "=2.2.0", optional = true}
wasmer-vm = {version = "2.2.0", optional = true}
wasmparser = "0.83.0"
#libmasp = { git = "https://github.com/anoma/masp", branch = "murisi/masp-incentive" }
masp_primitives = { git = "https://github.com/anoma/masp", rev = "bee40fc465f6afbd10558d12fe96eb1742eee45c" }
masp_proofs = { git = "https://github.com/anoma/masp", rev = "bee40fc465f6afbd10558d12fe96eb1742eee45c" }
zeroize = "1.5.5"

[dev-dependencies]
assert_matches = "1.5.0"
async-trait = {version = "0.1.51"}
byte-unit = "4.0.13"
libsecp256k1 = {git = "https://github.com/heliaxdev/libsecp256k1", rev = "bbb3bd44a49db361f21d9db80f9a087c194c0ae9"}
pretty_assertions = "0.7.2"
# A fork with state machine testing
proptest = {git = "https://github.com/heliaxdev/proptest", branch = "tomas/sm"}
test-log = {version = "0.2.7", default-features = false, features = ["trace"]}
tokio = {version = "1.8.2", default-features = false, features = ["rt", "macros"]}
tracing-subscriber = {version = "0.3.7", default-features = false, features = ["env-filter", "fmt"]}
